import Image from 'next/image';
import Link from 'next/link';
import {products,services} from '@/lib/content';
import {pageMetadata} from '@/lib/seo';
import {ProductCard,Tags} from '@/components/product-card';
import {Reel} from '@/components/motion';
import {InteractiveGrid} from '@/components/interactive-grid';
export const metadata=pageMetadata('Home','Quality before brand. Products worth using for years. Discover KIKAE’s selected tools, industrial products, safety products and measuring instruments.','/','banner.png');
export default function Home(){return <>
 <section className="hero" aria-label="KIKAE — Tools Become Culture"><InteractiveGrid/><h1 className="sr-only">KIKAE — Tools Become Culture</h1><Image className="hero-mark" src="/assets/banner.png" alt="KIKAE — Tools Become Culture" width={1260} height={588} priority sizes="(max-width:809px) 140vw, 925px"/><div className="hero-copy"><p>We don&apos;t sell every tool.</p><p><strong>We select the right ones.</strong></p></div><p className="hero-tagline">Quality before brand. Products worth using for years.</p></section>
 <div className="reel" data-reveal><Reel/></div>
 <section className="section" id="works"><h2 className="section-title" data-reveal>WHAT WE SELECT</h2><nav className="category-nav" aria-label="Product categories">{products.map((p,i)=><a href={`#${p.slug}`} key={p.slug}>0{i+1} — {p.title}</a>)}</nav><div className="products">{products.map(p=><article className="product-row" key={p.slug} id={p.slug} data-reveal><div className="product-description"><p>{p.description}</p><Tags product={p}/></div><ProductCard product={p}/></article>)}</div></section>
 <section className="section services" id="services"><h2 className="section-title wide" data-reveal>WHAT WE DO</h2><p className="eyebrow">/For Our Partners</p>{services.map(([title,description],i)=><article className="service-row" data-reveal key={title}><span className="number">0{i+1}</span><h3>{title}</h3><p>{description}</p></article>)}</section>
 <section className="section why"><h2 className="section-title why-title" data-reveal>WHY KIKAE</h2><p className="eyebrow">/How I Work</p><div className="manifesto" data-reveal><p>We choose quality over recognition.</p><p>Every product is selected for its<br className="desktop-break"/> quality, durability, usability, and reliability.</p><p>Only products worth using make it to KIKAE.</p></div><div className="market" data-reveal><Image src="/assets/market.png" alt="Quality products selected by KIKAE" width={1374} height={1145} sizes="(max-width:809px) 100vw, 50vw"/><div><h3>FROM PRODUCT TO MARKET</h3><p>We understand products through real-world use and market experience.</p><p>From product selection and localization to distribution, marketing, and customer support, KIKAE builds the path between quality manufacturers and the Korean market.</p><p>Good products deserve the right market.</p><Link className="button" href="/contact">Contact Now <span aria-hidden="true">↗</span></Link></div></div></section>
 </>}
