import {getTranslator} from '@/lib/language';
import Image from 'next/image';
import Link from 'next/link';
import {localizeProducts,services} from '@/lib/content';
import {pageMetadata} from '@/lib/seo';
import {ProductCard,Tags} from '@/components/product-card';
import {Reel} from '@/components/motion';
import {InteractiveGrid} from '@/components/interactive-grid';
export async function generateMetadata(){return pageMetadata('Home','Quality before brand. Products worth using for years. Discover KIKAE’s selected tools, industrial products, safety products and measuring instruments.','/','banner.png');}
export default async function Home(){const t=await getTranslator();const products=localizeProducts(t);return <>
 <section className="hero" aria-label={t("KIKAE — Tools Become Culture")}><InteractiveGrid/><h1 className="sr-only">{t("KIKAE — Tools Become Culture")}</h1><Image className="hero-mark" src="/assets/banner.png" alt={t("KIKAE — Tools Become Culture")} width={1260} height={588} priority sizes="(max-width:809px) 140vw, 925px"/><div className="hero-copy"><p>{t("We don't sell every tool.")}</p><p><strong>{t("We select the right ones.")}</strong></p></div><p className="hero-tagline">{t("Quality before brand. Products worth using for years.")}</p></section>
 <div className="reel" data-reveal><Reel label={t('Animated typography reel')}/></div>
 <section className="section" id="works"><h2 className="section-title" data-reveal>{t("WHAT WE SELECT")}</h2><nav className="category-nav" aria-label={t("Product categories")}>{products.map((p,i)=><a href={`#${p.slug}`} key={p.slug}>0{i+1} — {p.title}</a>)}</nav><div className="products">{products.map(p=><article className="product-row" key={p.slug} id={p.slug} data-reveal><div className="product-description"><p>{p.description}</p><Tags product={p}/></div><ProductCard product={p}/></article>)}</div></section>
 <section className="section services" id="services"><h2 className="section-title wide" data-reveal>{t("WHAT WE DO")}</h2><p className="eyebrow">{t("/For Our Partners")}</p>{services.map(([title,description],i)=><article className="service-row" data-reveal key={title}><span className="number">0{i+1}</span><h3>{t(title)}</h3><p>{t(description)}</p></article>)}</section>
 <section className="section why"><h2 className="section-title why-title" data-reveal>{t("WHY KIKAE")}</h2><p className="eyebrow">{t("/How I Work")}</p><div className="manifesto" data-reveal><p>{t("We choose quality over recognition.")}</p><p>{t("Every product is selected for its")}<br className="desktop-break"/>{' '}{t("quality, durability, usability, and reliability.")}</p><p>{t("Only products worth using make it to KIKAE.")}</p></div><div className="market" data-reveal><Image src="/assets/market.png" alt={t("Quality products selected by KIKAE")} width={1374} height={1145} sizes="(max-width:809px) 100vw, 50vw"/><div><h3>{t("FROM PRODUCT TO MARKET")}</h3><p>{t("We understand products through real-world use and market experience.")}</p><p>{t("From product selection and localization to distribution, marketing, and customer support, KIKAE builds the path between quality manufacturers and the Korean market.")}</p><p>{t("Good products deserve the right market.")}</p><Link className="button" href="/contact">{t("Contact Now")}<span aria-hidden="true">↗</span></Link></div></div></section>
 </>}
